name: Build Gradle project

on:
  push

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Add executable permission to gradlew
        run: chmod +x ./gradlew
      - name: Publish snapshot
        if: github.ref_name != 'main' && startsWith(github.ref, 'refs/tags/v') == false
        uses: gradle/gradle-build-action@v2.3.3
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        with:
          arguments: publish

      - name: Publish release
        if: github.ref_name != 'main' && startsWith(github.ref, 'refs/tags/v')
        uses: gradle/gradle-build-action@v2.3.3
        env:
          VERSION: ${{ github.ref_name }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        with:
          arguments: publish
