name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Add executable permission to gradlew
        run: chmod +x ./gradlew
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: -b ci.gradle package
